# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Clima' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clima
   pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire'
    pod 'SVProgressHUD'

end
